### ISSUE TITLE
App error in first line import app after build

### ISSUE THREAD

**Issue by DanielMaceira** [Batajus/electron-typescript-guide#3]
Hi! I've downloaded this electron-typescript-guide (thank you!) and I need to generate installers.

I've added electron-builder package as devDependencies, made changes on line 11 ("main") (because I got another error that can't find build/index.js) and added line 20 ("dist") as bellow. All other files is as it was downloaded.

```json
{
    "name": "electron-typescript-guide",
    "version": "0.0.1",
    "description": "This is a sample project for peoples, who want to start with Electron in combination with Typescript",
    "author": {
        "name": "Batajus"
    },
    "main": "src/index.ts",
    "scripts": {
        "compile": "tsc && copyfiles -f src/index.html build",
        "start": "npm run compile && electron .",
        "dist": "build"
    },
    "dependencies": {},
    "devDependencies": {
        "copyfiles": "^2.4.0",
        "electron": "^10.1.3",
        "electron-builder": "^22.10.5",
        "typescript": "^4.0.3"
    }
}
```

The build is succeed, but the example app doesn't open with error bellow:
```
A JavaScript error occurred in the main process
Uncaught Exception:
/Volumes/electron-typescript-guide 0.0.1/electron-typescript-guide.app/Contents/Resources/app.asar/src/index.ts:1
import { app, BrowserWindow } from 'electron';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1051:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:779:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:3494)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3698)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
```

<img width="531" alt="Captura de Tela 2021-04-14 às 14 39 17" src="https://user-images.githubusercontent.com/808077/114754762-4e713d80-9d2f-11eb-9922-40f74e77e40d.png">

I'm running on Mac osx and npm version 7.9.0.
Someone can help me?

**Comment by Batajus** [comment]
Hey, 
I'm very happy you like my project 😃  I tried to reproduce your error, but the `dist` script from the `package.json` didn't work for me, so I adjusted it.

My `package.json` looks like this now:
```
{
    "name": "electron-typescript-guide",
    "version": "0.0.1",
    "description": "This is a sample project for peoples, who want to start with Electron in combination with Typescript",
    "author": {
        "name": "Batajus"
    },
    "main": "build/index.js",
    "build": {
        "files": [
            "build"
        ]
    },
    "scripts": {
        "compile": "tsc && copyfiles -f src/index.html build && copyfiles -f package.json build",
        "start": "npm run compile && electron .",
        "dist": "npm run compile && electron-builder"
    },
    "devDependencies": {
        "copyfiles": "^2.4.0",
        "electron": "^10.1.3",
        "electron-builder": "^22.10.5",
        "typescript": "^4.0.3"
    }
}
```

To make it run I only added the `build` part and called the electron-builder itself in the `dist` script. Also I'm now copying the package.json to the build directory, too.

I hope this helps you, if not please tell me 😉

**Comment by Batajus** [comment]
The issue is closed due to inactivity
